version: '3'
services:
  db:
    image: mysql:8.0.19
    volumes:
     - ./data-init/scripts:/docker-entrypoint-initdb.d
     - ./data-init/files:/var/lib/mysql-files
    environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: debatsido
        MYSQL_USER: user
        MYSQL_PASSWORD: password
    ports:
       - "3306:3306"
    restart: always
    command:
      - '--character-set-server=utf8mb4'
      - '--secure-file-priv=/var/lib/mysql-files'

  api:
    image: pcourbin/debatsido_api:0.1.0
    build: ./api/DebatIDOAPI
    volumes:
     - ./api/DebatIDOAPI/DebatIDOAPI:/usr/src/app/DebatIDOAPI #For development
    environment:
        DATABASE_URL: "mysql://user:password@db:3306/debatsido"
        PORT: "3000"
    ports:
      - 4000:3000
    depends_on:
      - db
    restart: always

  front:
    image: pcourbin/debatsido_front:0.1.0
    build: ./front/DebatIDOFront
    volumes:
     - ./front/DebatIDOFront:/app #For development
     - ./environment.ts:/app/src/environments/environment.ts #For deployments
    ports:
      - 3000:4200
    depends_on:
      - db
      - api
    restart: always

  dbadmin:
    image: phpmyadmin/phpmyadmin:edge-4.9
    environment:
        #PMA_ARBITRARY: 1
        PMA_HOST: db
        MPA_PORT: 3306
        PMA_USER: user
        PMA_PASSWORD: password
    ports:
       - "8100:80"
