# Please, run docker-dev-prepare.sh before.
version: '3'
services:
  api:
    image: pcourbin/debatido_api:0.1.0
    build: ./DebatIDOAPI
    volumes:
     - ./DebatIDOAPI/DebatIDOAPI:/usr/src/app/DebatIDOAPI #For development
    environment:
        DATABASE_URL: "mysql://user:password@db:3306/debatsido"
        PORT: "3000"
    ports:
      - 4000:3000
    restart: always
