# Please, run docker-dev-prepare.sh before.
version: '3'
services:
  api:
    image: pcourbin/debatido_api:0.1.0
    build:
      context: ./out/DebatIDOAPI-python-flask
      dockerfile: Dockerfile
    volumes:
      - ./out/DebatIDOAPI-python-flask/DebatIDOAPI:/usr/src/app/DebatIDOAPI #For development
    environment:
        DATABASE_URL: "mysql://user:password@db:3306/db_test"
        PORT: "8080"
    ports:
      - 8000:8080s
