# Please, run docker-dev-prepare.sh before.
version: '3'
services:
  api:
    image: pcourbin/debatido_api:0.1.0
    build:
      context: ./out/DebatIDOAPI-python-flask
      dockerfile: Dockerfile
  #  volumes:
  #    - .:/usr/src/app
  #  environment:
  #    - PL_ENV_TYPE=local #local, release (docker-compose exec pl python3 manage.py createsuperuser), db
    ports:
      - 8000:8080
